/* 
 * DISCLAIMER PLACEHOLDER 
 */

package com.ogprover.pp.tp.ndgcondition;

import java.util.Vector;

import com.ogprover.pp.tp.OGPTP;
import com.ogprover.pp.tp.geoconstruction.Point;

/**
* <dl>
* <dt><b>Class description:</b></dt>
* <dd>Class for NDG (Non-degenerative) conditions generated by the area method</dd>
* </dl>
* 
* @version 1.00
* @author Damien Desfontaines
*/
public abstract class SimpleNDGCondition {
	/*
	 * ======================================================================
	 * ========================== VARIABLES =================================
	 * ======================================================================
	 */
	/**
	 * <i><b>
	 * Version number of class in form xx.yy where
	 * xx is major version/release number and yy is minor
	 * release number.
	 * </b></i>
	 */
	public static final String VERSION_NUM = "1.00"; // this should match the version number from class comment
	
	/**
	 * Theorem protocol that contains this NDG condition
	 */
	protected OGPTP consProtocol = null;
	
	/**
	 * Points involved in the NDG condition
	 */
	protected Vector<Point> points = null;
	
	
	/*
	 * ======================================================================
	 * ========================== GETTERS/SETTERS ===========================
	 * ======================================================================
	 */
	/**
	 * @return the consProtocol
	 */
	public OGPTP getConsProtocol() {
		return consProtocol;
	}

	/**
	 * @return the points involved in the NDG condition
	 */
	public Vector<Point> getPoints() {
		return points;
	}
	
	
	/*
	 * ======================================================================
	 * ========================= ABSTRACT METHODS ===========================
	 * ======================================================================
	 */
	/**
	 * @return a string describing the NDG condition
	 */
	public abstract String print();
}